apiVersion: v1
kind: Service
metadata:
  name: offline-service-service
spec:
  selector:
    app: offline-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP 
