apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: localhost:5000/api_gateway  
          # imagePullPolicy: Never
          ports:
            - containerPort: 8889
          env:
            - name: PORT
              value: "8889"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_HOST
              value: kafka-svc.kafka.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway-service
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
  type: LoadBalancer 