apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-gateway-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/microservice-cafe-be/api-gateway
