export const USER_REPOSITORY = "USER_REPOSITORY";
export const PEMISSION_ROLE_REPOSITORY = "PEMISSION_ROLE_REPOSITORY";
export const ROLE_REPOSITORY = "ROLE_REPOSITORY";
export const PERMISSION_REPOSITORY = "PERMISSION_REPOSITORY"
