export const ORDER_REPOSITORY = "ORDER_REPOSITORY";
export const CUSTOMER_REPOSITORY = "CUSTOMER_REPOSITORY";
export const CUSTOMER_ADDRESS_REPOSITORY = "CUSTOMER_ADDRESS_REPOSITORY";
export const ORDER_DETAIL_REPOSITORY = "ORDER_DETAIL_REPOSITORY";
export const PAYMENT_REPOSITORY = "PAYMENT_REPOSITORY";
export const SHIPMENT_ONLINE_REPOSITORY = "SHIPMENT_ONLINE_REPOSITORY";
