apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-service-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/microservice-cafe-be/auth-services
