apiVersion: v1
kind: Service
metadata:
  name: online-service-service
spec:
  selector:
    app: online-service
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP 
