apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-service
  labels:
    app: online-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-service
  template:
    metadata:
      labels:
        app: online-service
    spec:
      containers:
        - name: online-service
          image: localhost:5000/online_service
          # imagePullPolicy: Never
          ports:
            - containerPort: 9002
          env:
            - name: PORT
              value: "9002"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_HOST
              value: kafka-svc.kafka.svc.cluster.local
            - name: DB_HOST
              value: "mysql-service.default.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "hnam23012002"
            - name: DB_DIALECT
              value: "mysql"
            - name: DB_NAME_DEVELOPMENT
              value: "online_service"
            - name: DB_NAME_PRODUCTION
              value: "online_service"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: online-service
  labels:
    app: online-service
spec:
  selector:
    app: online-service
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP
